"""Localization utilities for AccountingBot."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class LanguagePack:
    code: str
    texts: Dict[str, str]

    def get(self, key: str) -> str:
        return self.texts.get(key, key)


_LANGUAGES = {
    "en": LanguagePack(
        code="en",
        texts={
            "start_message": "Hello! I'm AccountingBot, your friendly finance assistant.",
            "start_command_overview": "Here’s what I can do. Choose a command:",
            "start_search_hint": "Need an ID? Use /search <name> to discover matches.",
            "start_cancel_hint": "Send /cancel at any time to stop the current action.",
            "help_label": "Show this guide again",
            "add_person": "Add a Contact",
            "add_debt": "Log a Charge",
            "pay_debt": "Record a Payment",
            "history": "View History",
            "search": "Find a Record",
            "language": "Change Language",
            "cancel": "Cancel",
            "prompt_person_identifier": "Who would you like to work with? Send their ID (for example 42 or #42) or a name to look up.",
            "person_id_hint": "If you typed a name, I’ll show matches—then send the exact ID you want.",
            "enter_person_name": "Please share the person's full name so I can add them.",
            "person_added": "{name} has been added successfully with ID #{id}.",
            "invalid_person_name": "That name looks empty. Please send a valid name.",
            "duplicate_person_name": '"{name}" is already on your list. Try a different name.',
            "enter_person_prompt": "Pick someone from the buttons below or send their name/ID.",
            "choose_selection_method": "How would you like to find the person?",
            "select_using_id": "Use ID",
            "select_using_menu": "Use Menu",
            "prompt_person_id": "Great! Send me the person's ID (e.g. 42 or #42).",
            "menu_prompt": "Choose someone from the list. Page {page}.",
            "menu_search_prompt": "Type a name to search for and I'll filter the list.",
            "menu_search_results": "Showing results for \"{query}\" — {count} match(es). Page {page}.",
            "menu_search_no_results": "I couldn't find anyone matching \"{query}\". Try again or go back.",
            "previous_page": "◀ Prev",
            "next_page": "Next ▶",
            "clear_search": "Clear search",
            "no_people": "I haven't met anyone yet. Add a contact to get started!",
            "enter_debt_amount": "How much does {name} owe? Please send a positive amount.",
            "enter_debt_description": "Add a short note if you'd like, or type /skip to move on.",
            "enter_payment_description": "Would you like to add a note for this payment? Send it now or type /skip.",
            "debt_recorded": "All set! {name} now owes {amount:.2f}. Current balance: {balance:.2f}.",
            "enter_payment_amount": "How much is {name} paying? Please send a positive amount.",
            "payment_recorded": "Payment saved. {name}'s balance is now {balance:.2f}.",
            "invalid_number": "That doesn't look like a positive number. Please try again.",
            "history_header": "Here is the activity log for {name}:",
            "history_item_debt": "➕ {amount:.2f} — {description} ({date})",
            "history_item_payment": "➖ {amount:.2f} — {description} ({date})",
            "history_empty": "No activity recorded just yet.",
            "prompt_date_range": "Share a date range as YYYY-MM-DD,YYYY-MM-DD or type /skip to view everything.",
            "invalid_date_range": "Hmm, that date range doesn't look right. Please use YYYY-MM-DD,YYYY-MM-DD or /skip.",
            "language_prompt": "Please choose the language you'd like me to use.",
            "language_updated": "Great! I'll continue in {language}.",
            "search_prompt": "Send a name or ID and I'll look it up.",
            "search_results": "Here’s what I found:",
            "not_found": "I couldn't find a match.",
            "action_cancelled": "No worries—I've cancelled that action.",
            "confirm_debt": "Please confirm charging {name} for {amount:.2f}.",
            "confirm_debt_with_description": "Please confirm charging {name} {amount:.2f} for \"{description}\".",
            "confirm_payment": "Please confirm recording a payment of {amount:.2f} from {name}.",
            "confirm_payment_with_description": "Please confirm recording a payment of {amount:.2f} from {name} for \"{description}\".",
            "confirm_instructions": 'Reply with "{confirm}" to save or "{back}" to adjust. Use /cancel to stop.',
            "confirm_invalid": 'I didn’t catch that. Please reply with "{confirm}" or "{back}".',
            "confirm_keyword": "confirm",
            "confirmed": "Done!",
            "dismiss": "Close",
            "back": "Go Back",
            "dashboard": "Dashboard",
            "dashboard_summary": "📊 Snapshot Overview",
            "total_debt": "Total charges",
            "total_payments": "Total payments",
            "outstanding_balance": "Outstanding balance",
            "top_debtors": "Largest balances",
            "no_debtors": "All clear—no outstanding balances!",
            "recent_transactions": "Recent activity",
            "no_transactions": "No recent activity to display.",
            "recent_transaction_debt": "➕ {name} — {amount:.2f} on {date} ({description})",
            "recent_transaction_payment": "➖ {name} — {amount:.2f} on {date} ({description})",
            "balance_debtor": "owes {amount:.2f}",
            "balance_creditor": "is owed {amount:.2f}",
            "balance_settled": "settled",
            "search_result_item": "{index}. {name} (#{id}) — {status} • {score}% match",
            "search_suggestions": "No direct matches. Perhaps you meant: {suggestions}?",
            "search_filters_hint": "Tip: Try filters such as \"balance>0\", \"debtors\", or enter an ID.",
            "language_prompt_codes": "Available languages: {codes}. Send the code you’d like me to use.",
        },
    ),
    "fa": LanguagePack(
        code="fa",
        texts={
            "start_message": "سلام! من AccountingBot هستم، همراه مالی شما.",
            "start_command_overview": "اینجا فهرست کارهایی است که می‌توانم انجام دهم. یکی از این دستورات را بفرستید:",
            "start_search_hint": "به شناسه نیاز دارید؟ از ‎/search <نام> برای پیدا کردن گزینه‌ها استفاده کنید.",
            "start_cancel_hint": "در هر زمان برای توقف عملیات ‎/cancel را بفرستید.",
            "help_label": "نمایش دوباره این راهنما",
            "add_person": "افزودن مخاطب",
            "add_debt": "ثبت بدهی جدید",
            "pay_debt": "ثبت پرداخت",
            "history": "مشاهده تاریخچه",
            "search": "جستجوی سوابق",
            "language": "تغییر زبان",
            "cancel": "انصراف",
            "prompt_person_identifier": "می‌خواهید با چه کسی کار کنید؟ شناسه او را (مثلاً 42 یا ‎#42) بفرستید یا نامش را بنویسید تا جستجو کنم.",
            "person_id_hint": "اگر نام ارسال کنید، نتایج را نشان می‌دهم—سپس شناسه دقیق موردنظر را بفرستید.",
            "enter_person_name": "لطفاً نام کامل شخص را برای افزودن ارسال کنید.",
            "person_added": "{name} با شناسه #{id} با موفقیت افزوده شد.",
            "invalid_person_name": "نام ارسال‌شده خالی است. لطفاً نام معتبری وارد کنید.",
            "duplicate_person_name": '«{name}» قبلاً ثبت شده است. نام دیگری را امتحان کنید.',
            "enter_person_prompt": "از میان دکمه‌ها انتخاب کنید یا نام/شناسه را ارسال نمایید.",
            "choose_selection_method": "چطور می‌خواهید فرد را پیدا کنید؟",
            "select_using_id": "با شناسه",
            "select_using_menu": "از فهرست",
            "prompt_person_id": "لطفاً شناسه شخص را ارسال کنید (مثلاً 42 یا #42).",
            "menu_prompt": "از فهرست زیر انتخاب کنید. صفحه {page}.",
            "menu_search_prompt": "نام مورد نظر را تایپ کنید تا فهرست را جستجو کنم.",
            "menu_search_results": "نتایج برای «{query}» — {count} مورد. صفحه {page}.",
            "menu_search_no_results": "چیزی مطابق «{query}» پیدا نشد. دوباره جستجو کنید یا بازگردید.",
            "previous_page": "◀ قبلی",
            "next_page": "بعدی ▶",
            "clear_search": "پاک‌کردن جستجو",
            "no_people": "هنوز شخصی اضافه نشده است. لطفاً ابتدا یک مخاطب ایجاد کنید!",
            "enter_debt_amount": "مبلغ بدهی {name} را ارسال کنید. عدد باید مثبت باشد.",
            "enter_debt_description": "در صورت تمایل توضیح کوتاهی بنویسید یا برای عبور /skip را وارد کنید.",
            "enter_payment_description": "اگر می‌خواهید برای این پرداخت توضیحی ثبت کنید بفرستید یا /skip را وارد کنید.",
            "debt_recorded": "ثبت شد! {name} اکنون {amount:.2f} بدهکار است. مانده فعلی: {balance:.2f}.",
            "enter_payment_amount": "مبلغ پرداخت {name} را ارسال کنید. عدد باید مثبت باشد.",
            "payment_recorded": "پرداخت ذخیره شد. مانده {name} اکنون {balance:.2f} است.",
            "invalid_number": "مقدار ارسال‌شده عدد مثبت معتبری نیست. دوباره امتحان کنید.",
            "history_header": "گزارش فعالیت‌های {name}:",
            "history_item_debt": "➕ {amount:.2f} — {description} ({date})",
            "history_item_payment": "➖ {amount:.2f} — {description} ({date})",
            "history_empty": "هنوز تراکنشی ثبت نشده است.",
            "prompt_date_range": "بازه تاریخ را به صورت YYYY-MM-DD,YYYY-MM-DD ارسال کنید یا برای نمایش همه /skip را بنویسید.",
            "invalid_date_range": "بازه تاریخ نامعتبر است. لطفاً از قالب YYYY-MM-DD,YYYY-MM-DD یا دستور /skip استفاده کنید.",
            "language_prompt": "لطفاً زبان مورد نظرتان را انتخاب کنید.",
            "language_updated": "عالی! از این پس به {language} ادامه می‌دهم.",
            "search_prompt": "نام یا شناسه‌ای را که می‌خواهید جستجو کنم ارسال کنید.",
            "search_results": "نتایج پیدا شده:",
            "not_found": "نتیجه‌ای پیدا نکردم.",
            "action_cancelled": "اشکالی ندارد؛ این عملیات لغو شد.",
            "confirm_debt": "آیا ثبت بدهی {amount:.2f} برای {name} را تأیید می‌کنید؟",
            "confirm_debt_with_description": "آیا ثبت بدهی {amount:.2f} برای {name} بابت «{description}» را تأیید می‌کنید؟",
            "confirm_payment": "آیا ثبت پرداخت {amount:.2f} از سوی {name} را تأیید می‌کنید؟",
            "confirm_payment_with_description": "آیا ثبت پرداخت {amount:.2f} از سوی {name} بابت «{description}» را تأیید می‌کنید؟",
            "confirm_instructions": 'برای ذخیره "{confirm}" و برای ویرایش "{back}" را بفرستید. برای توقف ‎/cancel را ارسال کنید.',
            "confirm_invalid": 'متوجه نشدم. لطفاً "{confirm}" یا "{back}" را پاسخ دهید.',
            "confirm_keyword": "تایید",
            "confirmed": "انجام شد!",
            "dismiss": "بستن",
            "back": "بازگشت",
            "dashboard": "داشبورد",
            "dashboard_summary": "📊 نمای کلی سریع",
            "total_debt": "جمع بدهی‌ها",
            "total_payments": "جمع پرداخت‌ها",
            "outstanding_balance": "مانده باز",
            "top_debtors": "بیشترین مانده‌ها",
            "no_debtors": "همه‌چیز صاف است؛ بدهی باز نداریم!",
            "recent_transactions": "فعالیت‌های اخیر",
            "no_transactions": "فعلاً تراکنش تازه‌ای وجود ندارد.",
            "recent_transaction_debt": "➕ {name} — {amount:.2f} در تاریخ {date} ({description})",
            "recent_transaction_payment": "➖ {name} — {amount:.2f} در تاریخ {date} ({description})",
            "balance_debtor": "بدهکار {amount:.2f}",
            "balance_creditor": "طلبکار {amount:.2f}",
            "balance_settled": "تسویه شده",
            "search_result_item": "{index}. {name} (#{id}) — {status} • میزان تطابق {score}٪",
            "search_suggestions": "نتیجه مستقیمی نبود. شاید منظور شما این گزینه‌هاست: {suggestions}؟",
            "search_filters_hint": "نکته: می‌توانید از فیلترهایی مانند «balance>0»، «debtors» یا وارد کردن شناسه استفاده کنید.",
            "language_prompt_codes": "زبان‌های موجود: {codes}. کد دلخواه را ارسال کنید.",
        },
    ),
}


def get_text(key: str, language: str) -> str:
    """Return the localized text for ``key`` and ``language``."""

    pack = _LANGUAGES.get(language, _LANGUAGES["en"])
    return pack.get(key)


def available_languages() -> Dict[str, str]:
    """Return the list of available language codes and human-readable titles."""

    return {"en": "English", "fa": "فارسی"}
