"""Localization utilities for AccountingBot."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class LanguagePack:
    code: str
    texts: Dict[str, str]

    def get(self, key: str) -> str:
        return self.texts.get(key, key)


_LANGUAGES = {
    "en": LanguagePack(
        code="en",
        texts={
            "start_message": "Hello! I'm AccountingBot—your friendly, professional finance assistant.",
            "start_command_overview": "Pick what you'd like to do:",
            "start_search_hint": "Need someone quickly? Pick ➕ Add Contact or log activity, then choose Use Menu to browse your contacts or enter an ID directly.",
            "start_cancel_hint": "Want to stop? Send /cancel or tap ✖️ Cancel at any time.",
            "add_person": "➕ Add Contact",
            "add_debt": "🧾 Log a Charge",
            "pay_debt": "💳 Record a Payment",
            "history": "📜 View History",
            "dashboard": "📊 Dashboard",
            "search": "🔍 Find a Record",
            "language": "🌐 Change Language",
            "list_people": "👥 All Contacts",
            "export_transactions": "📁 Export Transactions",
            "cancel": "✖️ Cancel",
            "prompt_person_identifier": "Who would you like to work with? Send their ID (for example 42 or #42) or a name to look up.",
            "person_id_hint": "If you typed a name, I’ll show matches—then send the exact ID you want.",
            "enter_person_name": "Please share the person's full name.",
            "person_added": "{name} has been added successfully with ID #{id}.",
            "invalid_person_name": "That name looks empty. Please send a valid name.",
            "duplicate_person_name": '"{name}" is already on your list. Try a different name.',
            "enter_person_prompt": "Pick someone from the buttons below or send their name/ID.",
            "choose_selection_method": "How would you like to find the person?",
            "select_using_id": "Use ID",
            "select_using_menu": "Use Menu",
            "prompt_person_id": "Great! Send me the person's ID (e.g. 42 or #42). You can always tap Use Menu if you'd rather browse.",
            "menu_prompt": "Choose someone from the list. Page {page}.",
            "menu_search_prompt": "Type a name to search for and I'll filter the list.",
            "menu_search_results": "Showing results for \"{query}\" — {count} match(es). Page {page}.",
            "menu_search_no_results": "I couldn't find anyone matching \"{query}\". Try again or go back.",
            "previous_page": "◀ Prev",
            "next_page": "Next ▶",
            "clear_search": "Clear search",
            "no_people": "I haven't met anyone yet. Add a contact to get started!",
            "person_id_or_menu_hint": "Please send a numeric ID (like 42 or #42) or tap Use Menu to browse your contacts.",
            "people_list_header": "Here are all contacts (newest first, total {count}):",
            "menu_enter_debt_details": "Now send the amount and description for {name} (e.g. 150 Lunch with client).",
            "menu_enter_payment_details": "Now send the payment amount and description for {name} (e.g. 75 Refund for supplies).",
            "enter_debt_amount": "How much does {name} owe? Please send a positive amount.",
            "enter_debt_description": "Add a short note if you'd like, or tap Skip to move on.",
            "enter_payment_description": "Add a note for this payment if needed, or tap Skip to continue.",
            "debt_recorded": "All set! {name} now owes {amount:.2f}. Current balance: {balance:.2f}.",
            "enter_payment_amount": "How much is {name} paying? Please send a positive amount.",
            "payment_recorded": "Payment saved. {name}'s balance is now {balance:.2f}.",
            "invalid_number": "That doesn't look like a positive number. Please try again.",
            "history_header": "Here is the activity log for {name}:",
            "history_item_debt": "➕ {amount:.2f} — {description} ({date})",
            "history_item_payment": "➖ {amount:.2f} — {description} ({date})",
            "history_empty": "No activity recorded just yet.",
            "prompt_date_range": "Share a date range as YYYY-MM-DD,YYYY-MM-DD or type /skip to view everything.",
            "invalid_date_range": "Hmm, that date range doesn't look right. Please use YYYY-MM-DD,YYYY-MM-DD or /skip.",
            "language_prompt": "Please choose the language you'd like me to use.",
            "language_updated": "Great! I'll continue in {language}.",
            "search_prompt": "Send a name or ID and I'll look it up.",
            "search_results": "Here’s what I found:",
            "not_found": "I couldn't find a match.",
            "action_cancelled": "All right—I've cancelled that action. Let me know how else I can help.",
            "confirm_debt": "Please confirm charging {name} for {amount:.2f}.",
            "confirm_debt_with_description": "Please confirm charging {name} {amount:.2f} for \"{description}\".",
            "confirm_payment": "Please confirm recording a payment of {amount:.2f} from {name}.",
            "confirm_payment_with_description": "Please confirm recording a payment of {amount:.2f} from {name} for \"{description}\".",
            "confirm_instructions": 'Use the buttons below to confirm or adjust, or reply with "{confirm}" / "{back}". Send /cancel to stop.',
            "confirm_invalid": 'I didn’t catch that. Please reply with "{confirm}" or "{back}".',
            "confirm_keyword": "confirm",
            "confirmed": "Done!",
            "dismiss": "Close",
            "back": "Go Back",
            "dashboard": "Dashboard",
            "dashboard_summary": "📊 Snapshot Overview",
            "total_debt": "Total charges",
            "total_payments": "Total payments",
            "outstanding_balance": "Outstanding balance",
            "top_debtors": "Largest balances",
            "no_debtors": "All clear—no outstanding balances!",
            "recent_transactions": "Recent activity",
            "no_transactions": "No recent activity to display.",
            "recent_transaction_debt": "➕ {name} — {amount:.2f} on {date} ({description})",
            "recent_transaction_payment": "➖ {name} — {amount:.2f} on {date} ({description})",
            "balance_debtor": "owes {amount:.2f}",
            "balance_creditor": "is owed {amount:.2f}",
            "balance_settled": "settled",
            "search_result_item": "{index}. {name} (#{id}) — {status} • {score}% match",
            "search_suggestions": "No direct matches. Perhaps you meant: {suggestions}?",
            "search_filters_hint": "Tip: Try filters such as \"balance>0\", \"debtors\", or enter an ID.",
            "language_prompt_codes": "Tap a button below or send a language code like EN.",
            "quick_debt_prompt": "To add a charge, send the person's ID, the amount, and a short description in one message.",
            "quick_debt_example": "Example: 42 150 Lunch with client",
            "quick_payment_prompt": "To log a payment, send the person's ID, the amount, and a short description in one message.",
            "quick_payment_example": "Example: #42 75 Refund for supplies",
            "quick_entry_invalid_format": "Please send ID, amount, and description separated by spaces (for example: 42 150 Groceries).",
            "quick_entry_invalid_id": "I couldn't read the ID. Use digits like 42 or #42.",
            "quick_entry_invalid_amount": "The amount should be a positive number such as 12.50.",
            "quick_entry_person_not_found": "I couldn't find anyone with that ID. Check the number and try again.",
            "cancel_anytime": "Send /cancel at any time to stop.",
            "skip_optional": "Skip",
            "export_success": "Here is the latest transaction export.",
            "export_error": "I couldn't generate the export right now. Please try again later.",
        },
    ),
    "fa": LanguagePack(
        code="fa",
        texts={
            "start_message": "سلام! من AccountingBot هستم، همراه مالی شما.",
            "start_command_overview": "از میان گزینه‌های زیر کاری را که می‌خواهید انجام دهید انتخاب کنید:",
            "start_search_hint": "به دنبال کسی هستید؟ هنگام ثبت عملیات گزینه «از فهرست» را بزنید تا مخاطبان را ببینید یا مستقیم شناسه را وارد کنید.",
            "start_cancel_hint": "می‌خواهید توقف کنید؟ هر زمان خواستید ‎/cancel را بفرستید یا روی ✖️ انصراف بزنید.",
            "add_person": "➕ افزودن مخاطب",
            "add_debt": "🧾 ثبت بدهی",
            "pay_debt": "💳 ثبت پرداخت",
            "history": "📜 مشاهده تاریخچه",
            "dashboard": "📊 داشبورد",
            "search": "🔍 جستجو",
            "language": "🌐 تغییر زبان",
            "list_people": "👥 فهرست مخاطبان",
            "export_transactions": "📁 دریافت خروجی تراکنش‌ها",
            "cancel": "✖️ انصراف",
            "prompt_person_identifier": "می‌خواهید با چه کسی کار کنید؟ شناسه او را (مثلاً 42 یا ‎#42) بفرستید یا نامش را بنویسید تا جستجو کنم.",
            "person_id_hint": "اگر نام ارسال کنید، نتایج را نشان می‌دهم—سپس شناسه دقیق موردنظر را بفرستید.",
            "enter_person_name": "لطفاً نام کامل شخص را ارسال کنید.",
            "person_added": "{name} با شناسه #{id} با موفقیت افزوده شد.",
            "invalid_person_name": "نام ارسال‌شده خالی است. لطفاً نام معتبری وارد کنید.",
            "duplicate_person_name": '«{name}» قبلاً ثبت شده است. نام دیگری را امتحان کنید.',
            "enter_person_prompt": "از میان دکمه‌ها انتخاب کنید یا نام/شناسه را ارسال نمایید.",
            "choose_selection_method": "چطور می‌خواهید فرد را پیدا کنید؟",
            "select_using_id": "با شناسه",
            "select_using_menu": "از فهرست",
            "prompt_person_id": "لطفاً شناسه شخص را ارسال کنید (مثلاً 42 یا #42). هر زمان خواستید می‌توانید «از فهرست» را انتخاب کنید.",
            "menu_prompt": "از فهرست زیر انتخاب کنید. صفحه {page}.",
            "menu_search_prompt": "نام مورد نظر را تایپ کنید تا فهرست را جستجو کنم.",
            "menu_search_results": "نتایج برای «{query}» — {count} مورد. صفحه {page}.",
            "menu_search_no_results": "چیزی مطابق «{query}» پیدا نشد. دوباره جستجو کنید یا بازگردید.",
            "previous_page": "◀ قبلی",
            "next_page": "بعدی ▶",
            "clear_search": "پاک‌کردن جستجو",
            "no_people": "هنوز شخصی اضافه نشده است. لطفاً ابتدا یک مخاطب ایجاد کنید!",
            "person_id_or_menu_hint": "لطفاً یک شناسه عددی (مثلاً 42 یا ‎#42) بفرستید یا روی «از فهرست» بزنید.",
            "people_list_header": "تمام مخاطبان (جدیدترین در بالا، {count} مورد):",
            "menu_enter_debt_details": "حالا مبلغ و توضیح مربوط به {name} را وارد کنید (مثلاً 150 ناهار با مشتری).",
            "menu_enter_payment_details": "حالا مبلغ پرداخت و توضیح مربوط به {name} را وارد کنید (مثلاً 75 بازپرداخت خرید).",
            "enter_debt_amount": "مبلغ بدهی {name} را ارسال کنید. عدد باید مثبت باشد.",
            "enter_debt_description": "در صورت تمایل توضیح کوتاهی بنویسید یا دکمه «رد کردن» را بزنید.",
            "enter_payment_description": "اگر لازم است توضیح پرداخت را بنویسید یا روی «رد کردن» بزنید.",
            "debt_recorded": "ثبت شد! {name} اکنون {amount:.2f} بدهکار است. مانده فعلی: {balance:.2f}.",
            "enter_payment_amount": "مبلغ پرداخت {name} را ارسال کنید. عدد باید مثبت باشد.",
            "payment_recorded": "پرداخت ذخیره شد. مانده {name} اکنون {balance:.2f} است.",
            "invalid_number": "مقدار ارسال‌شده عدد مثبت معتبری نیست. دوباره امتحان کنید.",
            "history_header": "گزارش فعالیت‌های {name}:",
            "history_item_debt": "➕ {amount:.2f} — {description} ({date})",
            "history_item_payment": "➖ {amount:.2f} — {description} ({date})",
            "history_empty": "هنوز تراکنشی ثبت نشده است.",
            "prompt_date_range": "بازه تاریخ را به صورت YYYY-MM-DD,YYYY-MM-DD ارسال کنید یا برای نمایش همه ‎/skip را بنویسید.",
            "invalid_date_range": "بازه تاریخ نامعتبر است. لطفاً از قالب YYYY-MM-DD,YYYY-MM-DD یا دستور ‎/skip استفاده کنید.",
            "language_prompt": "لطفاً زبان مورد نظرتان را انتخاب کنید.",
            "language_updated": "عالی! از این پس به {language} ادامه می‌دهم.",
            "search_prompt": "نام یا شناسه‌ای را که می‌خواهید جستجو کنم ارسال کنید.",
            "search_results": "نتایج پیدا شده:",
            "not_found": "نتیجه‌ای پیدا نکردم.",
            "action_cancelled": "باشه — این عملیات لغو شد. هر زمان خواستید ادامه دهیم خبر بدهید.",
            "confirm_debt": "آیا ثبت بدهی {amount:.2f} برای {name} را تأیید می‌کنید؟",
            "confirm_debt_with_description": "آیا ثبت بدهی {amount:.2f} برای {name} بابت «{description}» را تأیید می‌کنید؟",
            "confirm_payment": "آیا ثبت پرداخت {amount:.2f} از سوی {name} را تأیید می‌کنید؟",
            "confirm_payment_with_description": "آیا ثبت پرداخت {amount:.2f} از سوی {name} بابت «{description}» را تأیید می‌کنید؟",
            "confirm_instructions": 'برای تایید یا ویرایش از دکمه‌های زیر استفاده کنید یا "{confirm}" / "{back}" را بفرستید. برای توقف ‎/cancel را ارسال کنید.',
            "confirm_invalid": 'متوجه نشدم. لطفاً "{confirm}" یا "{back}" را پاسخ دهید.',
            "confirm_keyword": "تایید",
            "confirmed": "انجام شد!",
            "dismiss": "بستن",
            "back": "بازگشت",
            "dashboard": "داشبورد",
            "dashboard_summary": "📊 نمای کلی سریع",
            "total_debt": "جمع بدهی‌ها",
            "total_payments": "جمع پرداخت‌ها",
            "outstanding_balance": "مانده باز",
            "top_debtors": "بیشترین مانده‌ها",
            "no_debtors": "همه‌چیز صاف است؛ بدهی باز نداریم!",
            "recent_transactions": "فعالیت‌های اخیر",
            "no_transactions": "فعلاً تراکنش تازه‌ای وجود ندارد.",
            "recent_transaction_debt": "➕ {name} — {amount:.2f} در تاریخ {date} ({description})",
            "recent_transaction_payment": "➖ {name} — {amount:.2f} در تاریخ {date} ({description})",
            "balance_debtor": "بدهکار {amount:.2f}",
            "balance_creditor": "طلبکار {amount:.2f}",
            "balance_settled": "تسویه شده",
            "search_result_item": "{index}. {name} (#{id}) — {status} • میزان تطابق {score}٪",
            "search_suggestions": "نتیجه مستقیمی نبود. شاید منظور شما این گزینه‌هاست: {suggestions}؟",
            "search_filters_hint": "نکته: می‌توانید از فیلترهایی مانند «balance>0»، «debtors» یا وارد کردن شناسه استفاده کنید.",
            "language_prompt_codes": "از دکمه‌های زیر استفاده کنید یا کد زبان (مثلاً FA) را بفرستید.",
            "quick_debt_prompt": "برای ثبت بدهی، شناسه شخص، مبلغ و توضیح کوتاه را در یک پیام بفرستید.",
            "quick_debt_example": "مثال: 42 150 کرایه تاکسی",
            "quick_payment_prompt": "برای ثبت پرداخت، شناسه شخص، مبلغ و توضیح کوتاه را در یک پیام بنویسید.",
            "quick_payment_example": "مثال: #42 75 بازپرداخت خرید",
            "quick_entry_invalid_format": "لطفاً شناسه، مبلغ و توضیح را با فاصله در یک پیام بفرستید (مثلاً: 42 150 خرید).",
            "quick_entry_invalid_id": "شناسه را متوجه نشدم. از عددی مثل 42 یا ‎#42 استفاده کنید.",
            "quick_entry_invalid_amount": "مبلغ باید یک عدد مثبت باشد؛ مثلاً 12.5.",
            "quick_entry_person_not_found": "فردی با این شناسه پیدا نشد. لطفاً شماره را بررسی کنید.",
            "cancel_anytime": "برای انصراف هر زمان خواستید ‎/cancel را بفرستید.",
            "skip_optional": "رد کردن",
            "export_success": "این هم خروجی تازه‌ی تراکنش‌ها.",
            "export_error": "متأسفم، الان نتوانستم خروجی بسازم. لطفاً کمی بعد دوباره امتحان کنید.",
        },
    ),
}


def get_text(key: str, language: str) -> str:
    """Return the localized text for ``key`` and ``language``."""

    pack = _LANGUAGES.get(language, _LANGUAGES["en"])
    return pack.get(key)


def available_languages() -> Dict[str, str]:
    """Return the list of available language codes and human-readable titles."""

    return {"en": "English", "fa": "فارسی"}
